version: '3.8'

services:
  web:
    image: stepaxvii/test_stripe:latest
    container_name: django_app_prod
    restart: always
    ports:
      - "8080:8000"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_SECRET_KEY_USD=${STRIPE_SECRET_KEY_USD}
      - STRIPE_SECRET_KEY_EUR=${STRIPE_SECRET_KEY_EUR}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - static_volume:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3

volumes:
  static_volume:
  db_volume:
