# Generated by Django 5.1.6 on 2025-02-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_discount_order_remove_tax_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
